### ISSUE TITLE
关于用cqhttp反代的一些问题

### ISSUE THREAD

**Issue by suhexia** [Hoshikawa-Kaguya/Sora#10]
尊敬的开发者您好，在我使用sora框架创建bot的时候我遇到了在反代上的一些问题，在bot的工程中我认为我的代码和您的是完全一致的（其实就是复制粘贴），在cqhttp中的配置如下，已经查阅过文档和问过相关人员均没有得到答案，所以想来请教一下您
![QQ截图20210120225645](https://user-images.githubusercontent.com/55019115/105192705-3de66800-5b30-11eb-8686-470e365bea15.png)
![QQ截图20210120225823](https://user-images.githubusercontent.com/55019115/105192753-40e15880-5b30-11eb-9f99-df8a2ed7e10b.png)

**Comment by Yukari316** [comment]
`go-cqhttp` 的请求路径设置错了
因为框架默认的请求路径是 `/`
所以将`go-cqhttp`设置选项中的`reverse_url`改为`ws://127.0.0.1:9200/`即可
