### ISSUE TITLE
请问在接收消息时，Newtonsoft在将JObject转换为ApiPrivateMsgEventArgs报错

### ISSUE THREAD

**Issue by GeekSheng** [Hoshikawa-Kaguya/Sora#12]
**使用环境**
 -  框架版本号:`0.5.3.1`
 -  运行环境:`win10X64 ARM`

**bug描述**
在接收消息时，Newtonsoft在将JObject转换为ApiPrivateMsgEventArgs报错，如果发送者只发一条文本消息的话，message只是一个字符串，同时我尝试发送图片和卡片消息都转换失败。

**错误截图或日志**
![image](https://user-images.githubusercontent.com/45655847/107815656-a1ba2480-6dae-11eb-9360-e26bc517c8c8.png)
![image](https://user-images.githubusercontent.com/45655847/107815725-b991a880-6dae-11eb-97db-ea9590255397.png)

**Comment by GeekSheng** [comment]
我的问题，没看清文档，同时也没自己看oneBot的文档，将go-cqhttp中的配置 post_message_format从String改为Array就好了

**Comment by Yukari316** [comment]
艹，我是不是要考虑弄个提示（
