### ISSUE TITLE
建议日志trigger command 显示类+方法名

### ISSUE THREAD

**Issue by NepPure** [Hoshikawa-Kaguya/Sora#19]
**使用环境**
 -  框架版本号:`0.7.0`
 -  运行环境:`windows`

![image](https://user-images.githubusercontent.com/12379907/110880633-e7203200-8319-11eb-943b-6bf541145f19.png)

**Comment by Yukari316** [comment]
会在下个版本进行支持

**Comment by Yukari316** [comment]
已支持 版本 `0.9.0`
