### ISSUE TITLE
[Feature Request] 插件化支持

### ISSUE THREAD

**Issue by NepPure** [Hoshikawa-Kaguya/Sora#20]
https://github.com/Yukari316/Sora/blob/f55ab9d8a4371973cbd867f49f818d4cc50c1e76/Sora/OnebotInterface/EventInterface.cs#L32-L38

大概就是启动的时候扫描指定目录动态加载dll，扫描注册特定Attribute的类和方法

静态插件化思考了下应该不复杂，不知道整个框架能否支持运行时新增插件

这样可以不停机更新部分模块业务逻辑，感觉好像会很好用୧(๑•̀◡•́๑)૭

**Comment by Yukari316** [comment]
外部插件的支持感觉从框架层去做支持的话。。。不是特别有必要
毕竟这个应该是应用层去做的
之前其实考虑过去支持插件，不过当时是没有特性指令，可以看一下这个PR #1 

不过现在也可以考虑将`MappingCommands`改为`Public`让用户去扫DLL文件
不是很确定要不要去支持

**Comment by xh321** [comment]
毕竟这只是一个SDK，嘛，又不是机器人客户端
不过可以做成类似中间件一样的东西（

**Comment by NepPure** [comment]
需求上也只是提一些想法，因为没有Roadmap，也不太好随便直接pr 233

**Comment by Yukari316** [comment]
应该会在下个版本提供外部dll扫描支持（ @xh321 在写了）
另外要不要来群里玩玩？（

**Comment by Yukari316** [comment]
已支持，版本 `0.9.0`
