### ISSUE TITLE
[Feature Request] asp.net core与依赖注入容器支持

### ISSUE THREAD

**Issue by NepPure** [Hoshikawa-Kaguya/Sora#21]
https://github.com/Yukari316/Sora/blob/f55ab9d8a4371973cbd867f49f818d4cc50c1e76/Sora/Command/CommandManager.cs#L215-L219

能够更方便的构架体系化业务？（鬼群友到底想干啥.jpg）

比如配合类似[ABP](https://github.com/aspnetboilerplate/aspnetboilerplate)这种框架一起用会很舒服，

目前这类框架做得好的好像都是python写的，我很看好Sora（大概是因为只会写C#）

**Comment by Yukari316** [comment]
https://github.com/Yukari316/Sora/blob/f55ab9d8a4371973cbd867f49f818d4cc50c1e76/Sora/Command/CommandManager.cs#L24-L28

这里面的`instanceDict`就是用来存放实例的，只不过这个字典只用于存放指令方法所属的实例，应该可以达到类似的效果（比如状态机这一类的东西）
框架自身应该不会考虑去支持IOC，因为IOC的话其实有其他轮子可以用，比如:`Unity`（这个轮子蛮好用的），毕竟重复造轮子其实不是很有必要（x

**Comment by wuyu8512** [comment]
> https://github.com/Yukari316/Sora/blob/f55ab9d8a4371973cbd867f49f818d4cc50c1e76/Sora/Command/CommandManager.cs#L215-L219
> 
> 能够更方便的构架体系化业务？（鬼群友到底想干啥.jpg）
> 
> 比如配合类似[ABP](https://github.com/aspnetboilerplate/aspnetboilerplate)这种框架一起用会很舒服，
> 
> 目前这类框架做得好的好像都是python写的，我很看好Sora（大概是因为只会写C#）

https://www.github.com/wuyu8512/NoAcg/tree/master/Wuyu.OneBot
稍微移植了一下，有需要可以看看

**Comment by ExerciseBook** [comment]
https://www.nuget.org/packages/OneBot-CommandRoute/ 
其实我一月份已经写过了，如果有什么改进建议的话，可以随时发 issue 或 pr。
