### ISSUE TITLE
命名空间污染

### ISSUE THREAD

**Issue by buger404** [Hoshikawa-Kaguya/Sora#35]
Sora.Entities.MessageElement.CQModel下的多个类名造成了命名空间污染，建议更名。
例如：
Image->CQImage
Text->CQText
...

**Comment by Yukari316** [comment]
框架在设计之初其实就考虑过这个问题，但是新的协议其实是要去除 `CQxxxx` 这样的字段的 （这个其实算是酷Q的历史遗留了）
并且 `CQModel` `CQCode` 等等这类的命名也会在正式版本由其他名称代替

不过现阶段应该不会对命名空间再做出修改

建议使用这样的定义来避免污染
```csharp
using CQImage = Sora.Entities.MessageElement.CQModel.Image;
```

**Comment by buger404** [comment]
好的
