### ISSUE TITLE
存在未知Bug

### ISSUE THREAD

**Issue by MuJint** [Hoshikawa-Kaguya/Sora#5]
**使用环境**
 -  框架版本号:``最新
 -  运行环境:``.net 5.0

**bug描述**
会出现异常bug直接闪退，不知道bug。解决办法，干掉你的强退逻辑，新开一个客户端重启。

**如何复现**
不知道

**错误截图或日志**
![image](https://user-images.githubusercontent.com/28145880/101338786-6b48c080-38b8-11eb-8448-720047c2f218.png)

**Comment by Yukari316** [comment]
一般如果出现强退问题是因为框架检测到了我的代码中或者是你的代码中有未被处理的异常

而且一般在VS的debug模式下如果发生了闪退窗口时不会被关闭的

所以我需要查看debug日志才能知道哪里出了问题

**Comment by MuJint** [comment]
是在发布版本上面，我需要瞅瞅计算机管理日志，如果没有那需要重新写日志复现了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;脆饼干&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月7日(星期一) 晚上10:06
收件人:&nbsp;&quot;Yukari316/Sora&quot;<Sora@noreply.github.com&gt;;
抄送:&nbsp;&quot;MuJint&quot;<1069430666@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Yukari316/Sora] 存在未知Bug (#5)
